# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task: docs
    # cmds:
    #   - echo "{{.GREETING}}"
    # silent: true
  docs:
    dir: assets/templates
    cmds:
      - libreoffice --headless --convert-to pdf *.doc
      - libreoffice --headless --convert-to pdf *.docx
