[project]
name = "scripts"
version = "0.1.0"
description = "Dependencies for scripts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "requests>=2.32.5",
]
